# Generated by Django 4.2.4 on 2023-10-06 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('masters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam_marks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Exam_type', models.CharField(max_length=100)),
                ('Exam_marks', models.CharField(max_length=20)),
                ('Student_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='masters.student')),
                ('Subject_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='masters.subject')),
            ],
        ),
    ]
